[site]

title = "Jinze Li"

description = """
Jinze Li | Undergraduate Researcher in Economics.
Urban Economics, Spatial Econometrics, AI and Spatial Data.
"""

favicon = "/favicon.svg"

last_updated = "July 2026"



[author]

name = "Jinze Li"

title = "Undergraduate Researcher in Economics"

institution = "Nanjing University"

avatar = "/bio.jpg"



[social]

email = "241098166@smail.nju.edu.cn"

location = "Nanjing, China"

google_scholar = ""

orcid = ""

github = "https://github.com/ljz060707-lang"

linkedin = ""



[features]

enable_likes = false

enable_one_page_mode = false



[i18n]

enabled = true

locales = ["en","zh"]

default_locale = "en"

mode = "auto"

switcher = true



[i18n.labels]

zh = "中文"

en = "English"



[[navigation]]

title = "About"

type = "page"

target = "about"

href = "/"



[[navigation]]

title = "Research"

type = "page"

target = "research"

href = "/research"



[[navigation]]

title = "Publications"

type = "page"

target = "publications"

href = "/publications"



[[navigation]]

title = "Projects"

type = "page"

target = "projects"

href = "/projects"



[[navigation]]

title = "CV"

type = "page"

target = "cv"

href = "/cv"
